git clone   https://github.com/nathanmarz/storm                                  
git clone   https://github.com/elasticsearch/elasticsearch                       
git clone   https://github.com/github/android                                    
git clone   https://github.com/JakeWharton/ActionBarSherlock                     
git clone   https://github.com/jfeinstein10/SlidingMenu                          
git clone   https://github.com/loopj/android-async-http                          
git clone   https://github.com/netty/netty                                       
git clone   https://github.com/JakeWharton/Android-ViewPagerIndicator            
git clone   https://github.com/clojure/clojure                                   
git clone   https://github.com/phonegap/phonegap-plugins                         
git clone   https://github.com/xamarin/XobotOS                                   
git clone   https://github.com/excilys/androidannotations                        
git clone   https://github.com/nicolasgramlich/AndEngine                         
git clone   https://github.com/Bearded-Hen/Android-Bootstrap                     
git clone   https://github.com/donnfelker/android-bootstrap                      
git clone   https://github.com/purplefox/vert.x                                  
git clone   https://github.com/SpringSource/spring-framework                     
git clone   https://github.com/Mojang/Minecraft-API                              
git clone   https://github.com/square/picasso                                    
git clone   https://github.com/facebook/presto                                   
git clone   https://github.com/chrisbanes/Android-PullToRefresh                  
git clone   https://github.com/jenkinsci/jenkins                                 
git clone   https://github.com/WhisperSystems/TextSecure                         
git clone   https://github.com/facebook/facebook-android-sdk                     
git clone   https://github.com/Netflix/RxJava                                    
git clone   https://github.com/springside/springside4                            
git clone   https://github.com/fernandezpablo85/scribe-java                      
git clone   https://github.com/nostra13/Android-Universal-Image-Loader           
git clone   https://github.com/cyrilmottier/GreenDroid                           
git clone   https://github.com/LMAX-Exchange/disruptor                           
git clone   https://github.com/chrisbanes/ActionBar-PullToRefresh                
git clone   https://github.com/libgdx/libgdx                                     
git clone   https://github.com/square/dagger                                     
git clone   https://github.com/johannilsson/android-pulltorefresh                
git clone   https://github.com/square/retrofit                                   
git clone   https://github.com/codahale/metrics                                  
git clone   https://github.com/androidquery/androidquery                         
git clone   https://github.com/etsy/AndroidStaggeredGrid                         
git clone   https://github.com/Netflix/Hystrix                                   
git clone   https://github.com/android/platform_frameworks_base                  
git clone   https://github.com/pcpratts/rootbeer1                                
git clone   https://github.com/chrisbanes/PhotoView                              
git clone   https://github.com/roboguice/roboguice                               
git clone   https://github.com/47deg/android-swipelistview                       
git clone   https://github.com/bauerca/drag-sort-listview                        
git clone   https://github.com/square/otto                                       
git clone   https://github.com/aporter/coursera-android                          
git clone   https://github.com/Bukkit/CraftBukkit                                
git clone   https://github.com/SimonVT/android-menudrawer                        
git clone   https://github.com/nhaarman/ListViewAnimations                       
git clone   https://github.com/JakeWharton/NineOldAndroids                       
git clone   https://github.com/arduino/Arduino                                   
git clone   https://github.com/codahale/dropwizard                               
git clone   https://github.com/gabrielemariotti/cardslib                         
git clone   https://github.com/spring-projects/spring-framework                  
git clone   https://github.com/greenrobot/EventBus                               
git clone   https://github.com/xetorthio/jedis                                   
git clone   https://github.com/astuetz/PagerSlidingTabStrip                      
git clone   https://github.com/nostra13/Android-Universal-Image-Loader           
git clone   https://github.com/keyboardsurfer/Crouton                            
git clone   https://github.com/processing-js/processing-js                       
git clone   https://github.com/chrisbanes/Android-PullToRefresh                  
git clone   https://github.com/gradle/gradle                                     
git clone   https://github.com/square/okhttp                                     
git clone   https://github.com/junit-team/junit                                  
git clone   https://github.com/Atmosphere/atmosphere                             
git clone   https://github.com/commonsguy/cw-omnibus                             
git clone   https://github.com/ACRA/acra                                         
git clone   https://github.com/twitter/ambrose                                   
git clone   https://github.com/yui/yuicompressor                                 
git clone   https://github.com/Netflix/SimianArmy                                
git clone   https://github.com/pakerfeldt/android-viewflow                       
git clone   https://github.com/OpenRefine/OpenRefine                             
git clone   https://github.com/JakeWharton/butterknife                           
git clone   https://github.com/k9mail/k-9                                        
git clone   https://github.com/jhy/jsoup                                         
git clone   https://github.com/clearspring/stream-lib                            
git clone   https://github.com/greenrobot/greenDAO                               
git clone   https://github.com/umano/AndroidSlidingUpPanel                       
git clone   https://github.com/vert-x/vert.x                                     
git clone   https://github.com/johannilsson/android-actionbar                    
git clone   https://github.com/JetBrains/intellij-community                      
git clone   https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition 
git clone   https://github.com/videlalvaro/gifsockets                            
git clone   https://github.com/Comcast/FreeFlow                                  
git clone   https://github.com/thinkaurelius/titan                               
git clone   https://github.com/ManuelPeinado/FadingActionBar                     
git clone   https://github.com/kaeppler/ignition                                 
git clone   https://github.com/hazelcast/hazelcast                               
git clone   https://github.com/twall/jna                                         
git clone   https://github.com/thinkaurelius/titan                               
git clone   https://github.com/octo-online/robospice                             
git clone   https://github.com/kevinsawicki/http-request                         
git clone   https://github.com/KentBeck/junit                                    
git clone   https://github.com/Netflix/SimianArmy                                
git clone   https://github.com/ChristopheVersieux/HoloEverywhere                 
git clone   https://github.com/nostra13/Android-Universal-Image-Loader           
git clone   https://github.com/thest1/LazyList                                   
git clone   https://github.com/square/android-times-square                       
git clone   https://github.com/douglascrockford/JSON-java                        
git clone   https://github.com/Bukkit/Bukkit                                     
git clone   https://github.com/novoda/android                                    
git clone   https://github.com/jgilfelt/android-viewbadger                       
git clone   https://github.com/qii/weiciyuan                                     
git clone   https://github.com/processing/processing                             
git clone   https://github.com/JakeWharton/Android-ViewPagerIndicator            
git clone   https://github.com/tjerkw/Android-SlideExpandableListView            
git clone   https://github.com/openaphid/android-flip                            
git clone   https://github.com/Athou/commafeed                                   
git clone   https://github.com/zxing/zxing                                       
git clone   https://github.com/Mikkeren/FizzBuzzEnterpriseEdition                
git clone   https://github.com/apache/cassandra                                  
git clone   https://github.com/tinkerpop/gremlin                                 
git clone   https://github.com/Netflix/curator                                   
git clone   https://github.com/commonsguy/cw-advandroid                          
git clone   https://github.com/Prototik/HoloEverywhere                           
git clone   https://github.com/MinecraftForge/MinecraftForge                     
git clone   https://github.com/quartzjer/TeleHash                                
git clone   https://github.com/emilsjolander/StickyListHeaders                   
git clone   https://github.com/pardom/ActiveAndroid                              
git clone   https://github.com/robovm/robovm                                     
git clone   https://github.com/Graylog2/graylog2-server                          
git clone   https://github.com/perwendel/spark                                   
git clone   https://github.com/typesafehub/config                                
git clone   https://github.com/jgilfelt/android-mapviewballoons                  
git clone   https://github.com/voldemort/voldemort                               
git clone   https://github.com/tinkerpop/blueprints                              
git clone   https://github.com/BonzaiThePenguin/WikiSort                         
git clone   https://github.com/facebook/hadoop-20                                
git clone   https://github.com/TooTallNate/Java-WebSocket                        
git clone   https://github.com/BoltsFramework/Bolts-Android                      
git clone   https://github.com/Atmosphere/atmosphere                             
git clone   https://github.com/romannurik/muzei                                  
git clone   https://github.com/koush/AndroidAsync                                
git clone   https://github.com/JakeWharton/DiskLruCache                          
git clone   https://github.com/Netflix/ice                                       
git clone   https://github.com/apache/incubator-cordova-android                  
git clone   https://github.com/maurycyw/StaggeredGridView                        
git clone   https://github.com/peter-lawrey/Java-Chronicle                       
git clone   https://github.com/derekbrameyer/android-betterpickers               
git clone   https://github.com/castorflex/SmoothProgressBar                      
git clone   https://github.com/yusuke/twitter4j                                  
git clone   https://github.com/korovyansk/android-fb-like-slideout-navigation    
git clone   https://github.com/koush/ion                                         
git clone   https://github.com/thomasst/mongoadmin                               
git clone   https://github.com/JakeWharton/ActionBarSherlock                     
git clone   https://github.com/apache/hadoop-common                              
git clone   https://github.com/commonsguy/cw-android                             
git clone   https://github.com/AsyncHttpClient/async-http-client                 
git clone   https://github.com/harism/android_page_curl                          
git clone   https://github.com/pahimar/Equivalent-Exchange-3                     
git clone   https://github.com/hibernate/hibernate-orm                           
git clone   https://github.com/Netflix/astyanax                                  
git clone   https://github.com/darvds/RibbonMenu                                 
git clone   https://github.com/rzwitserloot/lombok                               
git clone   https://github.com/goldmansachs/gs-collections                       
git clone   https://github.com/novoda/ImageLoader                                
git clone   https://github.com/0xdata/h2o                                        
git clone   https://github.com/mortardata/mortar-recsys                          
git clone   https://github.com/oschina/android-app                               
git clone   https://github.com/jgilfelt/android-sqlite-asset-helper              
git clone   https://github.com/inmite/android-styled-dialogs                     
git clone   https://github.com/JakeWharton/scalpel                               
git clone   https://github.com/romainguy/ViewServer                              
git clone   https://github.com/JakeWharton/u2020                                 
git clone   https://github.com/yinwang0/pysonar2                                 
git clone   https://github.com/mongodb/mongo-java-driver                         
git clone   https://github.com/apache/mahout                                     
git clone   https://github.com/afollestad/Cards-UI                               
git clone   https://github.com/commonsguy/cwac-endless                           
git clone   https://github.com/jeresig/processing-js                             
git clone   https://github.com/twitter/commons                                   
git clone   https://github.com/MovingBlocks/Terasology                           
git clone   https://github.com/nathanmarz/storm-starter                          
git clone   https://github.com/square/spoon                                      
git clone   https://github.com/eclipse/vert.x                                    
git clone   https://github.com/calabash/calabash-android                         
git clone   https://github.com/chewiebug/GCViewer                                
git clone   https://github.com/rstudio/rstudio                                   
git clone   https://github.com/mozilla/rhino                                     
git clone   https://github.com/mariotaku/twidere                                 
git clone   https://github.com/apache/lucene-solr                                
git clone   https://github.com/cloudera/oryx                                     
git clone   https://github.com/redsolution/xabber-android                        
git clone   https://github.com/cucumber/cucumber-jvm                             
git clone   https://github.com/jackpal/Android-Terminal-Emulator                 
git clone   https://github.com/robotmedia/AndroidBillingLibrary                  
git clone   https://github.com/FasterXML/jackson-core                            
git clone   https://github.com/grails/grails-core                                
git clone   https://github.com/JakeWharton/ActionBarSherlock                     
git clone   https://github.com/emilsjolander/StickyListHeaders                   
git clone   https://github.com/notnoop/java-apns                                 
git clone   https://github.com/JetBrains/kotlin                                  
git clone   https://github.com/jayway/maven-android-plugin                       
git clone   https://github.com/todoroo/astrid                                    
git clone   https://github.com/lucasr/smoothie                                   
git clone   https://github.com/dropwizard/dropwizard                             
git clone   https://github.com/mongodb/mongo-hadoop                              
git clone   https://github.com/MikeOrtiz/TouchImageView                          
git clone   https://github.com/richardwilly98/elasticsearch-river-mongodb        
git clone   https://github.com/jfeinstein10/JazzyViewPager                       
git clone   https://github.com/jjoe64/GraphView                                  
git clone   https://github.com/gwtbootstrap/gwt-bootstrap                        
git clone   https://github.com/flavienlaurent/NotBoringActionBar                 
git clone   https://github.com/sikuli/sikuli                                     
git clone   https://github.com/http-kit/http-kit                                 
git clone   https://github.com/geometer/FBReaderJ                                
git clone   https://github.com/Todd-Davies/ProgressWheel                         
git clone   https://github.com/ChristopheVersieux/HoloEverywhere                 
git clone   https://github.com/pingpongboss/StandOut                             
git clone   https://github.com/kikoso/android-stackblur                          
git clone   https://github.com/jberkel/sms-backup-plus                           
git clone   https://github.com/yixia/VitamioBundle                               
git clone   https://github.com/path/android-priority-jobqueue                    
git clone   https://github.com/johnkil/Android-AppMsg                            
git clone   https://github.com/pivotal/robolectric                               
git clone   https://github.com/orientechnologies/orientdb                        
git clone   https://github.com/gitblit/gitblit                                   
git clone   https://github.com/Espiandev/ShowcaseView                            
git clone   https://github.com/apache/hbase                                      
git clone   https://github.com/gitgrimbo/android-sliding-menu-demo               
git clone   https://github.com/Gottox/socket.io-java-client                      
git clone   https://github.com/apache/cordova-android                            
git clone   https://github.com/alibaba/fastjson                                  
git clone   https://github.com/foxykeep/DataDroid                                
git clone   https://github.com/6wunderkinder/android-sliding-layer-lib           
git clone   https://github.com/reactor/reactor                                   
git clone   https://github.com/gephi/gephi                                       
git clone   https://github.com/pedrovgs/DraggablePanel                           
git clone   https://github.com/jasonpolites/gesture-imageview                    
git clone   https://github.com/vrapper/vrapper                                   
git clone   https://github.com/sonatype/async-http-client                        
git clone   https://github.com/dinocore1/DevsmartLib-Android                     
git clone   https://github.com/daCapricorn/ArcMenu                               
git clone   https://github.com/jayway/robotium                                   
git clone   https://github.com/beworker/pinned-section-listview                  
git clone   https://github.com/TonicArtos/StickyGridHeaders                      
git clone   https://github.com/erikwt/PullToRefresh-ListView                     
git clone   https://github.com/robolectric/robolectric                           
git clone   https://github.com/siyamed/android-satellite-menu                    
git clone   https://github.com/linkedin/rest.li                                  
git clone   https://github.com/dim-s/jphp                                        
git clone   https://github.com/getlantern/lantern                                
git clone   https://github.com/lorensiuswlt/NewQuickAction                       
git clone   https://github.com/mixi-inc/AndroidTraining                          
git clone   https://github.com/nadavfima/cardsui-for-android                     
git clone   https://github.com/ansjsun/ansj_seg                                  
git clone   https://github.com/owncloud/android                                  
git clone   https://github.com/webbit/webbit                                     
git clone   https://github.com/SpringSource/spring-security-oauth                
git clone   https://github.com/romannurik/Android-MonthCalendarWidget            
git clone   https://github.com/amplab/tachyon                                    
git clone   https://github.com/spullara/mustache.java                            
git clone   https://github.com/jersey/jersey                                     
git clone   https://github.com/liquibase/liquibase                               
git clone   https://github.com/Netflix/servo                                     
git clone   https://github.com/ManuelPeinado/RefreshActionItem                   
git clone   https://github.com/sirthias/parboiled                                
git clone   https://github.com/apigee/usergrid-stack                             
git clone   https://github.com/apache/incubator-storm                            
git clone   https://github.com/thiagolocatelli/android-uitableview               
git clone   https://github.com/kevinweil/elephant-bird                           
git clone   https://github.com/lewish/asciiflow                                  
git clone   https://github.com/zeromq/jeromq                                     
git clone   https://github.com/ether/pad                                         
git clone   https://github.com/openplans/OpenTripPlanner                         
git clone   https://github.com/chrisbanes/Android-BitmapCache                    
git clone   https://github.com/RadiusNetworks/android-ibeacon-service            
git clone   https://github.com/jfeinstein10/SlidingMenu                          
git clone   https://github.com/paddybyers/anode                                  
git clone   https://github.com/SirSengir/BuildCraft                              
git clone   https://github.com/MasDennis/Rajawali                                
git clone   https://github.com/saik0/UnifiedPreference                           
git clone   https://github.com/alibaba/dubbo                                     
git clone   https://github.com/eclipse-color-theme/eclipse-color-theme           
git clone   https://github.com/SimonVT/android-menudrawer                        
git clone   https://github.com/loopj/android-smart-image-view                    
git clone   https://github.com/chrisjenx/Calligraphy                             
git clone   https://github.com/neo4j/community                                   
git clone   https://github.com/spring-projects/spring-boot                       
git clone   https://github.com/metamx/druid                                      
git clone   https://github.com/eishay/jvm-serializers                            
git clone   https://github.com/pwnall/chromeview                                 
git clone   https://github.com/fearofcode/bateman                                
git clone   https://github.com/JodaOrg/joda-time                                 
git clone   https://github.com/gabrielemariotti/androiddev                       
git clone   https://github.com/wyouflf/xUtils                                    
git clone   https://github.com/nathanmarz/storm-contrib                          
git clone   https://github.com/yangfuhai/afinal                                  
git clone   https://github.com/danieloeh/AntennaPod                              
git clone   https://github.com/chrislacy/TweetLanes                              
git clone   https://github.com/sephiroth74/ImageViewZoom                         
git clone   https://github.com/brianfrankcooper/YCSB                             
git clone   https://github.com/MichaelEvans/ColorArt                             
git clone   https://github.com/sirthias/pegdown                                  
git clone   https://github.com/forcedotcom/phoenix                               
git clone   https://github.com/edmodo/cropper                                    
git clone   https://github.com/linkedin/datafu                                   
git clone   https://github.com/emilsjolander/sprinkles                           
git clone   https://github.com/mttkay/ignition                                   
git clone   https://github.com/rtyley/roboguice-sherlock                         
git clone   https://github.com/CyanogenMod/android_frameworks_base               
git clone   https://github.com/mybatis/mybatis-3                                 
git clone   https://github.com/Flowdalic/asmack                                  
git clone   https://github.com/linkedin/databus                                  
git clone   https://github.com/mtoader/google-go-lang-idea-plugin                
git clone   https://github.com/ervandew/eclim                                    
git clone   https://github.com/dodola/android_waterfall                          
git clone   https://github.com/eddieringle/android-undergarment                  
git clone   https://github.com/apache/zookeeper                                  
git clone   https://github.com/AlibabaTech/druid                                 
git clone   https://github.com/jankotek/MapDB                                    
git clone   https://github.com/matburt/mobileorg-android                         
git clone   https://github.com/stephanenicolas/Quality-Tools-for-Android         
git clone   https://github.com/Dempsy/Dempsy                                     
git clone   https://github.com/lucasr/twoway-view                                
git clone   https://github.com/chrisbanes/photup                                 
git clone   https://github.com/JetBrains/ideavim                                 
git clone   https://github.com/Frege/frege                                       
git clone   https://github.com/NanoHttpd/nanohttpd                               
git clone   https://github.com/zxing/zxing                                       
git clone   https://github.com/jbossas/jboss-as                                  
git clone   https://github.com/liferay/liferay-portal                            
git clone   https://github.com/JohnPersano/SuperToasts                           
git clone   https://github.com/JakeWharton/SwipeToDismissNOA                     
git clone   https://github.com/jeeeyul/eclipse-themes                            
git clone   https://github.com/openhab/openhab                                   
git clone   https://github.com/cyrilmottier/Polaris                              
git clone   https://github.com/akquinet/android-archetypes                       
git clone   https://github.com/square/fest-android                               
git clone   https://github.com/BuildCraft/BuildCraft                             
git clone   https://github.com/oakes/Nightcode                                   
git clone   https://github.com/Activiti/Activiti                                 
git clone   https://github.com/facebook/buck                                     
git clone   https://github.com/killme2008/Metamorphosis                          
git clone   https://github.com/ManuelPeinado/MultiChoiceAdapter                  
git clone   https://github.com/hamcrest/JavaHamcrest                             
git clone   https://github.com/nutzam/nutz                                       
git clone   https://github.com/LarsWerkman/QuickReturnListView                   
git clone   https://github.com/JoanZapata/android-iconify                        
git clone   https://github.com/dreamhead/moco                                    
git clone   https://github.com/github/gauges-android                             
git clone   https://github.com/groovy/groovy-core                                
git clone   https://github.com/nostra13/Android-Universal-Image-Loader           
git clone   https://github.com/PomepuyN/BlurEffectForAndroidDesign               
git clone   https://github.com/joscha/play-authenticate                          
git clone   https://github.com/jgrapht/jgrapht                                   
git clone   https://github.com/koush/UrlImageViewHelper                          
git clone   https://github.com/Netflix/Priam                                     
git clone   https://github.com/fqrouter/fqrouter                                 
git clone   https://github.com/apache/solr                                       
git clone   https://github.com/facebook/rebound                                  
git clone   https://github.com/alexruiz/fest-assert-2.x                          
git clone   https://github.com/Issacw0ng/SwipeBackLayout                         
git clone   https://github.com/flatland/drip                                     
git clone   https://github.com/allwefantasy/ServiceFramework                     
git clone   https://github.com/SammyIAm/Moppy                                    
git clone   https://github.com/bigbluebutton/bigbluebutton                       
git clone   https://github.com/dmitry-zaitsev/AndroidSideMenu                    
git clone   https://github.com/jgilfelt/SystemBarTint                            
git clone   https://github.com/Netflix/eureka                                    
git clone   https://github.com/jodoglevy/gargl                                   
git clone   https://github.com/RomainPiel/Shimmer-android                        
git clone   https://github.com/FasterXML/jackson-databind                        
git clone   https://github.com/madeye/gaeproxy                                   
git clone   https://github.com/OnlyInAmerica/OpenSpritz-Android                  
git clone   https://github.com/rgladwell/m2e-android                             
git clone   https://github.com/foursquare/twofishes                              
git clone   https://github.com/amlcurran/ShowcaseView                            
git clone   https://github.com/linkedin/sensei                                   
git clone   https://github.com/nuvolabase/orientdb                               
git clone   https://github.com/SpringSource/spring-android-samples               
git clone   https://github.com/aws/aws-sdk-java                                  
git clone   https://github.com/wildfly/wildfly                                   
git clone   https://github.com/jprante/elasticsearch-river-jdbc                  
git clone   https://github.com/brettwooldridge/HikariCP                          
git clone   https://github.com/reactor/reactor                                   
git clone   https://github.com/iPaulPro/aFileChooser                             
git clone   https://github.com/mattdesl/lwjgl-basics                             
git clone   https://github.com/puniverse/quasar                                  
git clone   https://github.com/romannurik/Android-SwipeToDismiss                 
git clone   https://github.com/ps3mediaserver/ps3mediaserver                     
git clone   https://github.com/alibaba/RocketMQ                                  
git clone   https://github.com/cloudera/flume                                    
git clone   https://github.com/daizhenjun/ImageFilterForAndroid                  
git clone   https://github.com/romainguy/road-trip                               
git clone   https://github.com/mrniko/netty-socketio                             
git clone   https://github.com/freezy/android-xbmcremote                         
git clone   https://github.com/ragunathjawahar/android-saripaar                  
git clone   https://github.com/rno/Android-ScrollBarPanel                        
git clone   https://github.com/koush/android-websockets                          
git clone   https://github.com/johnkil/Android-ProgressFragment                  
git clone   https://github.com/tokudu/AndroidPushNotificationsDemo               
git clone   https://github.com/QuantumBadger/RedReader                           
git clone   https://github.com/OpenTSDB/opentsdb                                 
git clone   https://github.com/SimonVT/MessageBar                                
git clone   https://github.com/mongodb/morphia                                   
git clone   https://github.com/agirbal/umongo                                    
git clone   https://github.com/JetBrains/MPS                                     
git clone   https://github.com/LarsWerkman/HoloColorPicker                       
git clone   https://github.com/EsotericSoftware/kryo                             
git clone   https://github.com/rtyley/agit                                       
git clone   https://github.com/passsy/android-HoloCircularProgressBar            
git clone   https://github.com/jblough/Android-Pdf-Viewer-Library                
git clone   https://github.com/huewu/PinterestLikeAdapterView                    
git clone   https://github.com/square/okio                                       
git clone   https://github.com/prefuse/Prefuse                                   
git clone   https://github.com/megamattron/SplinterNet                           
git clone   https://github.com/miniway/jeromq                                    
git clone   https://github.com/ManuelPeinado/GlassActionBar                      
git clone   https://github.com/yangfuhai/afinal                                  
git clone   https://github.com/jfinal/jfinal                                     
git clone   https://github.com/BroadleafCommerce/BroadleafCommerce               
git clone   https://github.com/shikhar/sshj                                      
git clone   https://github.com/JakeWharton/Android-DirectionalViewPager          
git clone   https://github.com/a-thomas/androidkickstartr                        
git clone   https://github.com/slapperwan/gh4a                                   
git clone   https://github.com/58code/Argo                                       
git clone   https://github.com/johnlindquist/angularjs-plugin                    
git clone   https://github.com/CloudStack/CloudStack                             
git clone   https://github.com/apache/hive                                       
git clone   https://github.com/jOOQ/jOOQ                                         
git clone   https://github.com/neo4j/neo4j                                       
git clone   https://github.com/commonsguy/cwac-camera                            
git clone   https://github.com/jankotek/MapDB                                    
git clone   https://github.com/energia/Energia                                   
git clone   https://github.com/write2munish/Akka-Essentials                      
git clone   https://github.com/menacher/java-game-server                         
git clone   https://github.com/jitsi/jitsi                                       
git clone   https://github.com/BoD/android-switch-backport                       
git clone   https://github.com/eoecn/android-app                                 
git clone   https://github.com/ginatrapani/todo.txt-touch                        
git clone   https://github.com/excilys/androidannotations                        
git clone   https://github.com/jankotek/JDBM3                                    
git clone   https://github.com/scobal/seyren                                     
git clone   https://github.com/f2prateek/progressbutton                          
git clone   https://github.com/flavienlaurent/discrollview                       
git clone   https://github.com/jeromevdl/android-holo-colors-idea-plugin         
git clone   https://github.com/schaloner/deadbolt-2                              
git clone   https://github.com/laforge49/JActor                                  
git clone   https://github.com/rmtheis/android-ocr                               
git clone   https://github.com/wakaleo/game-of-life                              
git clone   https://github.com/neo4j/neo4j                                       
git clone   https://github.com/WhisperSystems/BitHub                             
git clone   https://github.com/ahorn/android-rss                                 
git clone   https://github.com/StevenRudenko/ActionsContentView                  
git clone   https://github.com/Jasig/cas                                         
git clone   https://github.com/jpardogo/ListBuddies                              
git clone   https://github.com/antlr/antlr4                                      
git clone   https://github.com/bumptech/glide                                    
git clone   https://github.com/M66B/XPrivacy                                     
git clone   https://github.com/thebuzzmedia/imgscalr                             
git clone   https://github.com/jhipster/generator-jhipster                       
git clone   https://github.com/square/mortar                                     
git clone   https://github.com/chrisjenx/ParallaxScrollView                      
git clone   https://github.com/mockito/mockito                                   
git clone   https://github.com/torquebox/torquebox                               
git clone   https://github.com/googlemaps/android-maps-utils                     
git clone   https://github.com/SpringSource/spring-mvc-showcase                  
git clone   https://github.com/flyingsaucerproject/flyingsaucer                  
git clone   https://github.com/lorensiuswlt/NewQuickAction3D                     
git clone   https://github.com/vekexasia/android-form-edittext                   
git clone   https://github.com/mobileresearch/weibo_android_sdk                  
git clone   https://github.com/jacobmoncur/QuiltViewLibrary                      
git clone   https://github.com/twotoasters/JazzyListView                         
git clone   https://github.com/ZhouWeikuan/cocos2d                               
git clone   https://github.com/brianm/jdbi                                       
git clone   https://github.com/entertailion/Fling                                
git clone   https://github.com/throrin19/Android-Validator                       
git clone   https://github.com/CyberAgent/android-gpuimage                       
git clone   https://github.com/woozzu/IndexableListView                          
git clone   https://github.com/bpellin/keepassdroid                              
git clone   https://github.com/dtolabs/rundeck                                   
git clone   https://github.com/turn/ttorrent                                     
git clone   https://github.com/datastax/java-driver                              
git clone   https://github.com/SpringSource/spring-security                      
git clone   https://github.com/couchbaselabs/TouchDB-Android                     
git clone   https://github.com/eclipse/jetty.project                             
git clone   https://github.com/FasterXML/jackson                                 
git clone   https://github.com/goldmansachs/gs-collections                       
git clone   https://github.com/bigbluebutton/bigbluebutton                       
git clone   https://github.com/spockframework/spock                              
git clone   https://github.com/twitter/hbc                                       
git clone   https://github.com/wwadge/bonecp                                     
git clone   https://github.com/dhanji/loop                                       
git clone   https://github.com/gaylemcd/ctci                                     
git clone   https://github.com/dynjs/dynjs                                       
git clone   https://github.com/commonsguy/cwac-merge                             
git clone   https://github.com/jmxtrans/jmxtrans                                 
git clone   https://github.com/UweTrottmann/SeriesGuide                          
git clone   https://github.com/amazonwebservices/aws-sdk-for-java                
git clone   https://github.com/foursquare/fongo                                  
git clone   https://github.com/jclouds/jclouds                                   
git clone   https://github.com/CyanogenMod/android_packages_apps_Apollo          
git clone   https://github.com/yinwang0/pysonar2                                 
git clone   https://github.com/square/seismic                                    
git clone   https://github.com/linkedin/indextank-engine                         
git clone   https://github.com/zxing/zxing                                       
git clone   https://github.com/tjake/Solandra                                    
git clone   https://github.com/cbeust/testng                                     
git clone   https://github.com/jenzz/Android-UndoBar                             
git clone   https://github.com/undertow-io/undertow                              
git clone   https://github.com/nicolasgramlich/AndEngineExamples                 
git clone   https://github.com/tomwhite/hadoop-book                              
git clone   https://github.com/emilsjolander/android-FlipView                    
git clone   https://github.com/hector-client/hector                              
git clone   https://github.com/unclebob/fitnesse                                 
git clone   https://github.com/nhaarman/supertooltips                            
git clone   https://github.com/MatthewYork/Colours                               
git clone   https://github.com/Diablo-D3/DiabloMiner                             
git clone   https://github.com/neofoniemobile/Crouton                            
git clone   https://github.com/flyway/flyway                                     
git clone   https://github.com/OSBI/saiku                                        
git clone   https://github.com/dain/leveldb                                      
git clone   https://github.com/gabrielemariotti/changeloglib                     
git clone   https://github.com/apache/cassandra                                  
git clone   https://github.com/commonsguy/cwac-loaderex                          
git clone   https://github.com/tinkerpop/rexster                                 
git clone   https://github.com/kilim/kilim                                       
git clone   https://github.com/github/maven-plugins                              
git clone   https://github.com/square/flow                                       
git clone   https://github.com/markushi/android-circlebutton                     
git clone   https://github.com/nvanbenschoten/motion                             
git clone   https://github.com/Espiandev/ShowcaseView                            
git clone   https://github.com/DozerMapper/dozer                                 
git clone   https://github.com/pents90/svg-android                               
git clone   https://github.com/sonyericssondev/ApkAnalyser                       
git clone   https://github.com/koush/ion                                         
git clone   https://github.com/kaeppler/droid-fu                                 
git clone   https://github.com/inmite/android-butterknife-zelezny                
git clone   https://github.com/code4craft/webmagic                               
git clone   https://github.com/roomorama/Caldroid                                
git clone   https://github.com/webbukkit/dynmap                                  
git clone   https://github.com/attenzione/android-ColorPickerPreference          
git clone   https://github.com/yahoo/storm-yarn                                  
git clone   https://github.com/wildabeast/BarcodeScanner                         
git clone   https://github.com/agoncal/agoncal-application-petstore-ee6          
git clone   https://github.com/puniverse/galaxy                                  
git clone   https://github.com/dbpedia-spotlight/dbpedia-spotlight               
git clone   https://github.com/astuetz/ViewPagerExtensions                       
git clone   https://github.com/JakeWharton/hugo                                  
git clone   https://github.com/rovo89/XposedBridge                               
git clone   https://github.com/CloudifySource/cloudify                           
git clone   https://github.com/jim618/multibit                                   
git clone   https://github.com/AndlyticsProject/andlytics                        
git clone   https://github.com/JodaOrg/joda-time                                 
git clone   https://github.com/JakeWharton/NotificationCompat2                   
git clone   https://github.com/JoanZapata/android-pdfview                        
git clone   https://github.com/linkedin/cleo                                     
git clone   https://github.com/twitter/twitter-text-java                         
git clone   https://github.com/sparklemotion/nokogiri                            
git clone   https://github.com/anismiles/websocket-android-phonegap              
git clone   https://github.com/spacecowboy/NotePad                               
git clone   https://github.com/Trinea/AndroidCommon                              
git clone   https://github.com/functionaljava/functionaljava                     
git clone   https://github.com/nicolas-raoul/Anki-Android                        
git clone   https://github.com/guardianproject/Gibberbot                         
git clone   https://github.com/thymeleaf/thymeleaf                               
git clone   https://github.com/taobao/TProfiler                                  
git clone   https://github.com/SpringSource/spring-hateoas                       
git clone   https://github.com/ManuelPeinado/GlassActionBar                      
git clone   https://github.com/Netflix/blitz4j                                   
git clone   https://github.com/petedoyle/android-support-v4-googlemaps           
git clone   https://github.com/jess-anders/two-way-gridview                      
git clone   https://github.com/koush/ion                                         
git clone   https://github.com/rnewson/couchdb-lucene                            
git clone   https://github.com/orfjackal/retrolambda                             
git clone   https://github.com/alibaba/druid                                     
git clone   https://github.com/neuland/jade4j                                    
git clone   https://github.com/maurycyw/StaggeredGridViewDemo                    
git clone   https://github.com/SpringSource/spring-test-mvc                      
git clone   https://github.com/cbeust/jcommander                                 
git clone   https://github.com/MostafaGazar/CustomShapeImageView                 
git clone   https://github.com/alibaba/zeus                                      
git clone   https://github.com/UweTrottmann/SeriesGuide                          
git clone   https://github.com/facebook/facebook-android-sdk                     
git clone   https://github.com/sqlcipher/android-database-sqlcipher              
git clone   https://github.com/metamx/druid                                      
git clone   https://github.com/jline/jline2                                      
git clone   https://github.com/eoecn/android-app                                 
git clone   https://github.com/kennyledet/Algorithm-Implementations              
git clone   https://github.com/impetus-opensource/Kundera                        
git clone   https://github.com/SonarSource/sonar                                 
git clone   https://github.com/mysema/querydsl                                   
git clone   https://github.com/romannurik/Android-WizardPager                    
git clone   https://github.com/facebook/buck                                     
git clone   https://github.com/encog/encog-java-core                             
git clone   https://github.com/qos-ch/logback                                    
git clone   https://github.com/Gregadeaux/android-fly-in-app-navigation          
git clone   https://github.com/lexs/android-delicious                            
git clone   https://github.com/nicoulaj/idea-markdown                            
git clone   https://github.com/arun-gupta/javaee7-samples                        
git clone   https://github.com/manmal/hn-android                                 
git clone   https://github.com/restlet/restlet-framework-java                    
git clone   https://github.com/nathanmarz/elephantdb                             
git clone   https://github.com/sk89q/worldedit                                   
git clone   https://github.com/johncarl81/parceler                               
git clone   https://github.com/OpenGrok/OpenGrok                                 
git clone   https://github.com/AlibabaTech/fastjson                              
git clone   https://github.com/commonsguy/cwac-wakeful                           
